# Generated by Django 3.1.7 on 2021-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='neighbouring_countries',
            field=models.JSONField(default=list),
        ),
    ]
