# Generated by Django 3.1.7 on 2021-12-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20211224_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.JSONField(default=list),
        ),
    ]
